[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cp -r frontend/public frontend/.next/standalone/frontend/public && cp -r frontend/.next/static frontend/.next/standalone/frontend/.next/static"

[deploy]
startCommand = "PORT=3000 node frontend/.next/standalone/frontend/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "zaproom-frontend"
