[build]
builder = "nixpacks"
buildCommand = "npm run build -w frontend"

[deploy]
startCommand = "npm start -w frontend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "zaproom-frontend"
